on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout MiKTeX 24.4
        uses: actions/checkout@v3
        with:
          repository: '1320014053/miktex' 
          ref: '123' 
          path: 'miktex' 

      - name: Install dependencies
        run: |
          brew update
          brew upgrade
          brew install cmake # 安装 cmake 
          brew install pkg-config
          brew install icu4c
          brew install binutils
          brew install freetype
          brew install cairo
          brew install fribidi
          brew install gmp
          brew install graphite2
          brew install boost
          brew install hunspell
          brew install jpeg
          brew install libpng
          brew install libtiff
          brew install libzzip
          brew install log4cxx
          brew install mpfr
          brew install openssl
          brew install pixman
          brew install popt
          brew install potrace
          brew install qt
          brew install poppler-qt5
          brew install mpfi
          brew install uriparser
          brew install xz
          # 根据 MiKTeX 24.4 文档安装其他必要依赖 

      - name: Configure and Build 
        run: |
          mkdir miktex/build
          cd miktex/build
          ls -all /usr/local/opt/qt/lib
          brewprefix="`brew --prefix`"
          export CMAKE_PREFIX_PATH="${brewprefix}/opt/icu4c:${brewprefix}/opt/openssl:${brewprefix}/opt/icu4c:${brewprefix}/opt/qt/lib/QtCore:${brewprefix}/opt/qt/lib/QtGui:${brewprefix}/opt/qt/lib/QtDBus:${brewprefix}/opt/qt/lib:${CMAKE_PREFIX_PATH}"
          export CURL_CA_BUNDLE="/etc/ssl/cert.pem"
          cmake ..
          #make package

      # 可选: 上传构建结果
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: miktex-build
          path: |
            miktex/build/ # 上传 build 目录下的所有文件
            /usr/local/opt/qt/
