on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout MiKTeX 24.4
        uses: actions/checkout@v3
        with:
          repository: '1320014053/miktex' 
          ref: '123' 
          path: 'miktex' 

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
