on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout MiKTeX 24.4
        uses: actions/checkout@v3
        with:
          repository: '1320014053/miktex' 
          ref: '123' 
          path: 'miktex' 

      - name: Setup Border0 action
        uses: borderzero/gh-action@v2
        with:
          token: ${{ secrets.BORDER0_ADMIN_TOKEN }}
          background-mode: true
